- name: Set up NodeSource
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Install Node.js package
  apt: pkg=nodejs update_cache=yes

- name: Install Grunt via npm
  npm: name=grunt-cli global=yes

- name: Install MEAN package via npm
  npm: name=mean-cli global=yes
